name: tour_management
description: Main application package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_bloc: ^5.0.0
  rxdart: ^0.23.1
  equatable: ^1.0.0
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.0.0
  fluttertoast: ^7.1.1
  intl: ^0.16.1
  datetime_picker_formfield: ^1.0.0
  flutter_rating_bar: ^3.2.0+1
  grouped_list: ^3.5.0
  image_picker: ^0.6.7+12
  chpnt_repo_manager:
    path: chpnt_repo_manager
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+2
  http: ^0.12.1
  url_launcher: ^5.7.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
